# Generated by Django 5.2 on 2025-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_offerprice_product_offers_product_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offers',
            new_name='offer1',
        ),
        migrations.AddField(
            model_name='product',
            name='offer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
