# Generated by Django 5.2 on 2025-04-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_offers_product_offer1_product_offer2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer1',
            new_name='offers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer3',
        ),
    ]
