# Generated by Django 5.2 on 2025-04-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_offer1_product_offers_remove_product_offer2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
    ]
