# Generated by Django 5.2 on 2025-04-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
