# Generated by Django 5.2 on 2025-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_quantity_cartitem_stock_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='stock',
            new_name='quantity',
        ),
    ]
