# Generated by Django 5.2 on 2025-05-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_delivery_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 15, 36, 19, 23256, tzinfo=datetime.timezone.utc)),
        ),
    ]
